# Generated by Django 4.2.8 on 2023-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VHStore', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(choices=[('simple', 'Simple'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=20),
        ),
    ]
