# Generated by Django 4.2.8 on 2023-12-26 18:17

import VHStore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VHStore', '0007_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(choices=[('simple', 'SIMPLE'), ('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(default=VHStore.models.StatusType['SIMPLE'], on_delete=django.db.models.deletion.CASCADE, to='VHStore.membershipstatus'),
        ),
    ]
