# Generated by Django 4.2.8 on 2023-12-26 18:21

from django.db import migrations, models
import django.db.models.deletion

from VHStore.models import StatusType, MembershipStatus


def add_status_types(apps, schema_editor):
    status_milestones = {
        StatusType.SIMPLE.value: 500,
        StatusType.BRONZE.value: 1000,
        StatusType.SILVER.value: 5000,
        StatusType.GOLD.value: 10000,
    }
    status_discounts = {
        StatusType.SIMPLE.value: 0,
        StatusType.BRONZE.value: 3,
        StatusType.SILVER.value: 5,
        StatusType.GOLD.value: 10,
    }
    for status_type in StatusType:
        MembershipStatus.objects.create(
            name=status_type.value,
            discount=status_discounts[status_type.value],
            milestone=status_milestones[status_type.value]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('VHStore', '0009_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VHStore.membershipstatus'),
        ),
        migrations.AddField(
            model_name='membershipstatus',
            name='milestone',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.RunPython(add_status_types)
    ]
